name: Publish documentation
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run doc && touch docs/.nojekyll
      - uses: niklasf/ghpages@initial-branch
        env:
          BUILD_DIR: 'docs/'
          GH_PAT: ${{ secrets.GH_PAT }}
