name: Publish documentation
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup node.js
      uses: actions/setup-node@v1
    - name: npm install, compile, test, generate docs
      run: |
        npm install
        npm run compile
        npm test
        npm run doc
    - name: GitHub pages deploy
      uses: maxheld83/ghpages@d79d57aa5f407fd3e0b06ed5b36a8d4fd74b8c1c
      env:
        BUILD_DIR: "docs/"
