name: Publish documentation
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run doc
      - run: |
          cd docs &&
          git init --initial-branch gh-pages &&
          git config user.name "${GITHUB_ACTOR}" &&
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" &&
          git add . &&
          git commit -m 'Deploy to GitHub Pages' &&
          git push --force "https://${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git" gh-pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
